### PR TITLE
Bump Tor to 0.4.8.11 from 0.4.8.9

### PR DESCRIPTION
**Pull request by bitmold**
Rebased the couple dozen or so GP commits on top of the `tor-0.4.8.11` tag. Was definitely one of the trickier git maneuvers I've had to do in some time.  

I'm not having any issues building and running this in my local tor-android, but would appreciate as many eyes on this as possible ! Thanks <3

### CODE REVIEW

**Comment by n8fr8** [comment]
@eighthave anything out of the ordinary here? Hoping to merge!

**Comment by eighthave** [comment]
As far as I remember, the workflow does not use pull requests at all.  I can't think how this could even be managed using pull requests, it doesn't seem feasible.  Or at least it would be quite complicated.

Instead, just make a local branch _tor-android-0.4.8.x_ based on the last tag, e.g. _tor-android-0.4.7.15_, then rebase that on a tor tag, e.g. _tor-0.4.8.11_, then tag it as _tor-android-0.4.8.11_.  I thought this was documented somewhere, like the README or something.
@uniqx?

**Comment by bitmold** [comment]
Not sure, but uniqx just made one for tor 0.4.8.9 and I copied their approach here

-------- Original Message --------

**Comment by uniqx** [comment]
I'm not aware of any documented workflow. My workflow is:

 * do a rebase/cherry-pick to graft changes for android on top of the targeted official tor tag
 * do a build to verify it's compiling (I seem to be getting away without any additional q.a. 😅)
 * do a PR to merge into guardianproject master branch, to make sure checkouts of this repository are up to date
 * push related tags

**Comment by n8fr8** [comment]
@bitmold we are going to have @uniqx do this update release since they have been handling this so far. Just want to make sure our workflow is consistent from release to release as much as possible. Thanks for showing the way and prompting us to get this done, and will merge the rest of your work on tor-android and Orbot this week.

**Pull request closed without merging**
