### PR TITLE
Tor android 0.4.8.7 dev

### PR DESCRIPTION
**Pull request by uniqx**
Re-based android specific changes on top of tor 0.4.8.7
I had to resolve some (luckily trivial) merge-conflicts for this re-base.

heads up: tor 0.4.8 seems to require rust. As far as I could see the geoip dependency now is built using rust: scripts/maint/geoip/README.geoip

### CODE REVIEW

**Comment by n8fr8** [comment]
Is the rust build working as expected?

**Comment by syphyr** [comment]
The generation of the geoip database is done by torproject before every release. Rust is not needed to build tor 0.4.8.

**Comment by n8fr8** [comment]
I'm having trouble merging this into master.

**Comment by syphyr** [comment]
> I'm having trouble merging this into master.

But also I think there is an unresolved issue with the backported android specific changes.

**Comment by syphyr** [comment]
I would suggest checking out the latest 0.4.8 tag and then cherry picking the android changes on top of that from here: https://github.com/syphyr/tor/commits/release-0.4.8

**Comment by syphyr** [comment]
@n8fr8 This should not be on the master branch anyway.  The master branch of tor is not the same as 0.4.8.x.  Each stable release should be on its own separate branch since the android specific changes can be different on each branch.

**Comment by n8fr8** [comment]
I was able to push this to a branch here: https://github.com/guardianproject/tor/tree/tor-android-0.4.8.7 and the build is working. going to test integration with tor-android make now.

**Pull request closed without merging**
